#!/usr/bin/env python3
"""Pull the book's exports into book/, pinned to one book commit.

Every test in this repository cites claims and hypotheses by their permanent
IDs (EE-C-nnnn, EE-H-nnnn) and runs against a pinned snapshot of the
registers, so a result always says which version of the book it tested.

Usage: python tools/sync_book.py [--ref main]
Writes book/*.json, book/SOURCE, and BACKLOG.md.
"""
import argparse
import json
import os
import urllib.request

REPO = "natanatan/Emergent-Existence"
SCHEMA = "emergent-existence-exports/1"
FILES = ["manifest.json", "claims.json", "hypotheses.json", "elements.json", "companion-backlog.json"]
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def get(url):
    with urllib.request.urlopen(url) as r:
        return json.load(r)


def backlog_md(backlog, commit):
    tested = set(os.listdir(os.path.join(HERE, "tests"))) if os.path.isdir(os.path.join(HERE, "tests")) else set()
    out = ["# Backlog",
           "",
           f"The hypotheses the book's register marks as testable here, from the exports at "
           f"[`{commit[:7]}`](https://github.com/{REPO}/tree/{commit}/exports). Generated by "
           "`tools/sync_book.py`; do not edit by hand. A hypothesis moves out of the backlog when "
           "`tests/<ID>/` exists.",
           "",
           "| ID | Hypothesis | Status | Resolved by | Test |",
           "| --- | --- | --- | --- | --- |"]
    for h in backlog:
        alias = f" ({', '.join(h['aliases'])})" if h["aliases"] else ""
        test = f"[`tests/{h['id']}`](tests/{h['id']})" if h["id"] in tested else "—"
        cells = [f"`{h['id']}`{alias}", h["hypothesis"] or "", h["status"] or h["status_text"] or "",
                 h["resolve_by"] or "", test]
        out.append("| " + " | ".join(c.replace("|", "\\|") for c in cells) + " |")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ref", default="main")
    a = ap.parse_args()
    commit = get(f"https://api.github.com/repos/{REPO}/commits/{a.ref}")["sha"]
    data = {n: get(f"https://raw.githubusercontent.com/{REPO}/{commit}/exports/{n}") for n in FILES}
    if data["manifest.json"].get("schema") != SCHEMA:
        raise SystemExit(f"exports schema is {data['manifest.json'].get('schema')!r}, expected {SCHEMA!r}")
    os.makedirs(os.path.join(HERE, "book"), exist_ok=True)
    for n, obj in data.items():
        with open(os.path.join(HERE, "book", n), "w", encoding="utf-8") as f:
            f.write(json.dumps(obj, ensure_ascii=False, indent=1) + "\n")
    with open(os.path.join(HERE, "book", "SOURCE"), "w") as f:
        f.write(f"{REPO}@{commit}\n")
    with open(os.path.join(HERE, "BACKLOG.md"), "w", encoding="utf-8") as f:
        f.write(backlog_md(data["companion-backlog.json"], commit))
    print(f"synced book exports at {commit[:7]}: {len(data['companion-backlog.json'])} hypotheses in the backlog")


if __name__ == "__main__":
    main()
