#!/usr/bin/env python3
"""Pull the book's exports into book/, pinned to one book commit.

Every test in this repository cites claims and hypotheses by their permanent
IDs (EE-C-nnnn, EE-H-nnnn) and runs against a pinned snapshot of the
registers, so a result always says which version of the book it tested.

Usage: python tools/sync_book.py [--ref main]
Writes book/*.json, book/SOURCE, and BACKLOG.md.
"""
import argparse
import json
import os
import re
import urllib.request

REPO = "natanatan/Emergent-Existence"
SCHEMA = "emergent-existence-exports/1"
FILES = ["manifest.json", "claims.json", "hypotheses.json", "elements.json", "companion-backlog.json"]
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def get(url):
    with urllib.request.urlopen(url) as r:
        return json.load(r)


def modules_by_id():
    """Which modules cite each ID in their SPEC.md."""
    found = {}
    root = os.path.join(HERE, "modules")
    for d in sorted(os.listdir(root)) if os.path.isdir(root) else []:
        spec = os.path.join(root, d, "SPEC.md")
        if d.startswith("_") or not os.path.exists(spec):
            continue
        for i in set(re.findall(r"EE-[CH]-\d{4}", open(spec, encoding="utf-8").read())):
            found.setdefault(i, []).append(d)
    return found


def backlog_md(backlog, commit):
    mods = modules_by_id()
    out = ["# Backlog",
           "",
           f"The Hypothesis Register entries marked `companion_testable`, from the book's exports at "
           f"[`{commit[:7]}`](https://github.com/{REPO}/tree/{commit}/exports), with the modules that bear on "
           "each. Generated by `tools/sync_book.py`; do not edit by hand.",
           "",
           "| ID | Hypothesis | Status | Resolved by | Modules |",
           "| --- | --- | --- | --- | --- |"]
    for h in backlog:
        alias = f" ({', '.join(h['aliases'])})" if h["aliases"] else ""
        m = ", ".join(f"[`{d}`](modules/{d})" for d in mods.get(h["id"], [])) or "—"
        cells = [f"`{h['id']}`{alias}", h["hypothesis"] or "", h["status"] or h["status_text"] or "",
                 h["resolve_by"] or "", m]
        out.append("| " + " | ".join(c.replace("|", "\\|") for c in cells) + " |")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ref", default="main")
    a = ap.parse_args()
    commit = get(f"https://api.github.com/repos/{REPO}/commits/{a.ref}")["sha"]
    data = {n: get(f"https://raw.githubusercontent.com/{REPO}/{commit}/exports/{n}") for n in FILES}
    if data["manifest.json"].get("schema") != SCHEMA:
        raise SystemExit(f"exports schema is {data['manifest.json'].get('schema')!r}, expected {SCHEMA!r}")
    os.makedirs(os.path.join(HERE, "book"), exist_ok=True)
    for n, obj in data.items():
        with open(os.path.join(HERE, "book", n), "w", encoding="utf-8") as f:
            f.write(json.dumps(obj, ensure_ascii=False, indent=1) + "\n")
    with open(os.path.join(HERE, "book", "SOURCE"), "w") as f:
        f.write(f"{REPO}@{commit}\n")
    with open(os.path.join(HERE, "BACKLOG.md"), "w", encoding="utf-8") as f:
        f.write(backlog_md(data["companion-backlog.json"], commit))
    print(f"synced book exports at {commit[:7]}: {len(data['companion-backlog.json'])} hypotheses in the backlog")


if __name__ == "__main__":
    main()
